### ISSUE TITLE
Receiving multiple discord notifications for the same movie/show when it's available 

### ISSUE THREAD

**Issue by TRaSH-** [petio-team/petio#394]
**Describe the bug**
Being that Petio doesn't sync with the *arr multiple people can request the same show/movie.
A good side effect of this option is that the end user can request it and get a notification when it's available.

But when it's available I don't think the Admin should get a notification for all users that requested it.
I only have family and 2 close friends that make use of it, but this can get annoying if you got a big user base and and theirs a popular show or movie and you get like 10+ notifications.

It's fine when you get a notification it's available but it isn't needed to get multiple ones for every user who requested it 

**To Reproduce**
Just request the same  show/movie by multiple users

**Expected behavior**
I expect that the Admin only get's 1 notification when it's available and not for all the users that have requested it.
actually the Admin only should get 2 notifications
1. when some request  a movie/show
2. when it's available.

**Screenshots**
![image](https://user-images.githubusercontent.com/6155095/116983132-03ad6a80-acca-11eb-8f1b-3f3393f471f0.png)

**Desktop (please complete the following information):**
In my opinion not relevant to this issue

**Smartphone (please complete the following information):**
In my opinion not relevant to this issue

**Additional context**

**Comment by AshDyson** [comment]
This will be fixed in the notification overhaul, currently the admin is just copied in to all emails as an alpha "testing" kind of mentality. Just so we as admin can see every email that is sent out for assurance its working. The new notification system will only email the admin once to say a request has been logged, then will only email the relative users when their requests become available. So for now I'm closing this but expect to see this resolved when the new notification system is built out. Any questions hit us up on discord!
