### ISSUE TITLE
FR: Download progress bar on requests.

### ISSUE THREAD

**Issue by ersan** [petio-team/petio#476]
Would be really cool if you could add a download progress bar to active requests (via sonarr and radarr's /queue endpoint), especially when they are auto-approved.

**Comment by AshDyson** [comment]
This already exists? In the admin view under a request each download is listed with a download status progress bar

**Comment by AshDyson** [comment]
![image](https://user-images.githubusercontent.com/28293531/124187730-2683b180-dab6-11eb-949b-ee8eff401686.jpeg)

**Comment by AshDyson** [comment]
Closing this feature request if you’ve anything to add please reply to re open it

**Comment by ersan** [comment]
I meant for the users requesting, not just admins.

**Comment by AshDyson** [comment]
Users can see which step their requests is up to on the requests page. We don’t have any plans to show live download info to end users as this will cause confusion. Just because something shows as 70% complete doesn’t mean it hasn’t stalled or needs processing etc so we just have more ambiguous stages instead

**Comment by ersan** [comment]
> Users can see which step their requests is up to on the requests page. We don’t have any plans to show live download info to end users as this will cause confusion. Just because something shows as 70% complete doesn’t mean it hasn’t stalled or needs processing etc so we just have more ambiguous stages instead

Ookay, it’s your project.
