### ISSUE TITLE
Petio Setup won't connect to MongoDB - no saslprep library specified

### ISSUE THREAD

**Issue by dominikpflegerl** [petio-team/petio#542]
During the setup, the MongoDB connection test fails. Logfile shows:

`2021-08-26 13:47:30 info: API: testing mongo connection: mongodb://petio:asdf@DockerServer:53035`
`(node:7092) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized`

Same Connection string works with MongoDB Compass on the same machine as Petio itself.
Test-NetConnection DockerServer -Port 53035 is also successful, so a connection issue isn't the problem.

Petio version 0.5.2-alpha
Operatin System: Windows Server 2022

MongoDB version 5.0.2 running as docker container with host network directly listening on 53035.

edit: Switched to MongoDB 4.4.8, no difference.

**Comment by beyondmeat** [comment]
I have both mongo latest and petio alpha running in containers and it works fine. Seems like an issue with your environment and not petio.

Are you using Linux containers or Windows containers? Use Linux.

Btw you shouldn't need to expose any ports to the host if both are docker containers and in the same docker network. I recommend reading up on how you can have 2 containers communicate with each other without needing the host ports. Use Traefik as a reverse proxy instead of nginx. I also recommend you use Linux instead of Windows as the host OS but that's another discussion, even docker using WSL2 (you have docker using WSL2 right???, Better check on this) Is still poor performance compared to Linux host and docker.

**Comment by dominikpflegerl** [comment]
I think you've misunderstood my environment, or my explanation isn't quite right. 😄 

I have 2 VMs:
1) Windows Server 2022 w/ Plex, Sonarr, Radarr and Petio running (I want to keep all Plex related apps on one machine)
2) Debian 11 w/ Docker and a MongoDB container for Petio

After some discussion and troubleshooting on the Discord server, I ended up disabling authentication on my MongoDB instance and letting Petio connect to it without any username and password, because there might be a problem with connection strings with passwords. A Dev on Discord said it's an issue between them and mongoose.
