### ISSUE TITLE
Release new docker dev builds to fix tv show pages

### ISSUE THREAD

**Issue by beyondmeat** [petio-team/petio#690]
**Describe the bug**
Tv show pages have an error loading so it's broken. Can't request TV show because the pages don't load 

**To Reproduce**
1. Go to '...' tv show
2. Click on '....' tv show
3. Scroll down to '....'nothing

**Expected behavior**
Works

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] don't matter
 - Browser [e.g. chrome, safari] don't matter
 - Version [e.g. 22] latest docker dev image available

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] pixel 3
 - Browser [e.g. stock browser, safari] chrome
 - Version [e.g. 22] latest

**Additional context**
Going through your commit history looks like you fixed it but you never released a new Dev build or anything.

Patio is quite unusable with this bug please release a fix ASAP.

It's like the docker Dev images are not being updated due to changes you're also fixing.

Please just make a new release with the fixes

**Comment by angrycuban13** [comment]
Unless you were told to switch to develop for a specific reason, you should not be using it. I recommend you switch back to the latest "stable" release.

Otherwise, you can switch to the `nightly` tag using Petio's official docker image as Hotio's image needs to update some stuff on his end and he will do so once the process is finished on our end.
