### ISSUE TITLE
latest(8af7a020) docker container does not contain arm64 arch

### ISSUE THREAD

**Issue by guliashvili** [petio-team/petio#859]
Currently, tagged latest docker image, https://github.com/petio-team/petio/pkgs/container/petio/214920072?tag=latest does not contain arm64 architecture image. Is there any chance you could add it? Thank you

**Comment by ADRFranklin** [comment]
@guliashvili I've pushed an image for you where the tag is `master` and not `latest` due to the way the old system is made, it's a challenging task to get it rebuild. 

There is one change that had to be made which I wasn't able to work around due to docker not fully respecting symlinks, which is that the volume for the config is now `/app/config` and not `/app/api/config`, so make sure to change that in your compose file.

let me know how you get on with it.

**Comment by guliashvili** [comment]
Oh wow, thank you so much for such a quick response.
